### ISSUE TITLE
不可信的旧时间戳 1970-01-01 08:00:00

### ISSUE THREAD

**Issue by JohnTian** [feiskyer/tensorflow-handbook#1]
[jt@AY130516154626455c20Z ~]$ TF_TYPE="cpu"
[jt@AY130516154626455c20Z ~]$ TARGET_DIRECTORY='/usr/local'
[jt@AY130516154626455c20Z ~]$ curl -L "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-$(go env GOOS)-x86_64-1.2.0.tar.gz" | sudo tar -C $TARGET_DIRECTORY -xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 9100k    0   622    0     0    513      0  5:02:45  0:00:01  5:02:44   514tar: ./include/tensorflow/c/c_api.h：不可信的旧时间戳 1970-01-01 08:00:00
tar: ./include/tensorflow/c：不可信的旧时间戳 1970-01-01 08:00:00
tar: ./include/tensorflow：不可信的旧时间戳 1970-01-01 08:00:00
tar: ./include：不可信的旧时间戳 1970-01-01 08:00:00
 87 9100k   87 7950k    0     0  3341k      0  0:00:02  0:00:02 --:--:-- 3340ktar: ./lib/libtensorflow.so：不可信的旧时间戳 1970-01-01 08:00:00
tar: ./lib：不可信的旧时间戳 1970-01-01 08:00:00
100 9100k  100 9100k    0     0  3509k      0  0:00:02  0:00:02 --:--:-- 3508k
tar: ./include/tensorflow/c/LICENSE：不可信的旧时间戳 1970-01-01 08:00:00
tar: .：不可信的旧时间戳 1970-01-01 08:00:00

**Comment by feiskyer** [comment]
系统时间不对？是不是系统时间太老了？

**Comment by JohnTian** [comment]
@feiskyer 我也不是很清楚哈，这个可以更新一下系统时间，就可以了么？我现在准备从源码进行编译了。

**Comment by feiskyer** [comment]
更新系统时间应该就可以了

**Comment by JohnTian** [comment]
本来想用tensorflow for go，刚看了一下官网，准备入坑tensorflow servering.
